### ISSUE TITLE
it's awesome but has memory reak problem (doesn't closing browsersubprocess)

### ISSUE THREAD

**Issue by MogsFriend** [ngld/OverlayPlugin#2]
after i found two plugins, and find some problem.
yeah, this plugin is perfect. 

@lalafellsleep has same issue, project(cefglue to cefsharp) for overlayplugin. it's like 'i need use newer chromium' and he find devtool bug ( https://github.com/cefsharp/CefSharp/issues/2264 ) and fixed it.

this plugin create new browser (overlay) and close then, successfully closed but didn't closed browsersubprocess (they has avg 30mb memory)

but https://github.com/Chau-Sara/Aliapoh.Overlay not have problem.

it'll fix it?

**Comment by MogsFriend** [comment]
same problem in plugin enable/disable
![image](https://user-images.githubusercontent.com/46330334/62254268-77ef1600-b433-11e9-8f1b-cfe627df3d3e.png)
one more en/disable
![image](https://user-images.githubusercontent.com/46330334/62254290-89d0b900-b433-11e9-900a-fb50c907c3eb.png)

they doesn't disposed.

**Comment by ngld** [comment]
The new release (0.4.0) partially fixes the issue. The CEF processes are properly disposed and the most memory is freed. However, some memory (~ 5 MiB) still leaks when you disable the plugin. I'm not sure if I can fix this since that would involve shutting down and unloading all addons as well.

This should only affect you if you repeatedly enable and disable the plugin. If you're trying to reset / restart it, restarting ACT is a better solution since that will actually reset it (disabling the plugin doesn't do that). Even if you disable the plugin, CEF (the browser engine) stays active as long as ACT runs. If I shut down CEF, I can't use it again until the next ACT restart.
