### ISSUE TITLE
Chinese version parse error and may stop working

### ISSUE THREAD

**Issue by chun1324** [ngld/OverlayPlugin#254]
After updating OverlayPlugin it stops logging any information. Also, there is an error message mention about game version 5.5 while it is currently 6.01. Please take a look into it. Thank you

FFXIV_ACT_Plugin.dll: 2.6.5.0
OverlayPlugin 0.18.2

Steps:
1. Plugins
2. FFXIV ACT Plugin
3. Parse Option
4. Language: 中文
5. General
6. Check the log
Error message:

```
Error: Failed to find enmity memory for 5.5: charmapAddress,inCombatAddress
Further enmity errors won't be logged.
```

**Comment by quisquous** [comment]
Ack, sorry.  I think this was my previous in combat changed that substituted 6.1 for 6.0.  I need to have kept 6.0 there as well.  EDIT: on second thought, the memory candidates are picked on language, so that just needs to be updated.  I'm honestly surprised the Korean version is working as it says 5.2.
