### ISSUE TITLE
Typing into an overlay does not work

### ISSUE THREAD

**Issue by unfaiyted** [ngld/OverlayPlugin#3]
Hey, 

I've been working on an overlay I want to use for something a little different than most of the other overlays (https://github.com/unfaiyted/find-my-treasure) I was using the existing OverlayPlugin but I saw that cactbot was looking to switch to this one so I looked into it some and it looks great.

I was looking to be able to type into an input when the overlay is locked, the problem is that it ignored the typing and types it into the main application. I believe this was purposeful and by design. Is there anyway that I can overcome this limitation? 

Thanks in advance!

**Comment by ngld** [comment]
Locking doesn't affect focus handling and as long as the overlay has focus, it'll receive keyboard input.
Make sure your overlay is focused (and not ACT).

**Comment by ngld** [comment]
I took another look at this. The overlay should never gain focus regardless of whether it's locked or not since `WS_EX_NOACTIVATE` is set on the window. However, interestingly enough, the overlay *does* gain focus if the main ACT window was focused before clicking on the overlay.

Sorry, I forgot about that part in my last message.

I'm not sure how to fix this without breaking expected behaviour for Kagerou and other overlays. The problem is that if I changed this, clicking on a tab in Kagerou would take your keyboard focus away from the game which means you'd have to click on the game again before you could execute commands there which is probably not what people expect by now.

I could probably make this an option though.

**Comment by unfaiyted** [comment]
That would be fantastic. I figured that was an intentional design feature. It it were an option that would be perfect.

**Comment by ngld** [comment]
I've just released 0.8.0. With that release you can call `OverlayPluginApi.setAcceptFocus(true);` in your overlay to accept focus and keyboard input. You can call the same method at any time with `false` to revert the change.
I thought this way you can completely control this yourself and don't have to tell users to enable a checkbox in their overlay settings or something similar.
