### ISSUE TITLE
Version issue 

### ISSUE THREAD

**Issue by HAERUHAERU** [ngld/OverlayPlugin#43]
Is there a reason why it should be the latest version of FFXIV_ACT_Plugin?
I want to use it on a Korean server, but it's not working. 

Is there no way?
I would like to distribute it to Korean users if possible.

(The plugin version for Korean servers is currently 1.7.2.10 and will soon be using 2.0.4.0.)

**Comment by ShadyWhite** [comment]
> Is there a reason why it should be the latest version of FFXIV_ACT_Plugin?
> I want to use it on a Korean server, but it's not working.
> 
> Is there no way?
> I would like to distribute it to Korean users if possible.
> 
> (The plugin version for Korean servers is currently 1.7.2.10 and will soon be using 2.0.4.0.)

It should work after 5.0 update of Korean server with FFXIV_ACT_Plugin 2.X+.Same as Chinese server.

**Comment by HAERUHAERU** [comment]
Thank you for answer. I have a question again.

There is a download related error in the OverlayPlugin Updater.
I get an exception message and download is very slow. 
Eventually a download failure message appears.

I think the overlay updater only works fine with the latest version (2.0.4.4). 
If you don't modify this part, it will be difficult to use on KR and CN servers maybe. 

Please let me know if there is a way I can fix this.

Environment :
FFXIV_ACT_Plugin: 2.0.4.0
OverlayPlugin.dll: 0.10.1.0
ACT: 3.4.5 Release 265
Windows 10
Installed VC Redist 2019, .NET

▼▼▼▼▼▼▼▼▼▼▼ Attach the log of the overlay plugin updater below. ▼▼▼▼▼▼▼▼▼▼▼

Downloading "https://github.com/ngld/OverlayPlugin/releases/download/v0.7.0/CefSharp-75.1.14-x64.DO_NOT_DOWNLOAD" into C:\Users\User\AppData\Roaming\Advanced Combat Tracker\OverlayPluginCef\OverlayPlugin.tmp\update.7z...
The download was interrupted: System.IO.IOException: 읽기 작업이 실패했습니다. 내부 예외를 참조하세요. ---> System.Net.WebException: 요청이 중단되었습니다. 요청이 취소되었습니다.
   위치: System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   위치: System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   --- 내부 예외 스택 추적의 끝 ---
   위치: System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   위치: RainbowMage.OverlayPlugin.Updater.Installer.<Download>d__8.MoveNext()
Resuming download...
The download was interrupted: System.IO.IOException: 읽기 작업이 실패했습니다. 내부 예외를 참조하세요. ---> System.Net.WebException: 요청이 중단되었습니다. 요청이 취소되었습니다.
   위치: System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   위치: System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   --- 내부 예외 스택 추적의 끝 ---
   위치: System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   위치: RainbowMage.OverlayPlugin.Updater.Installer.<Download>d__8.MoveNext()
Resuming download...
The download was interrupted: System.IO.IOException: 읽기 작업이 실패했습니다. 내부 예외를 참조하세요. ---> System.Net.WebException: 요청이 중단되었습니다. 요청이 취소되었습니다.
   위치: System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   위치: System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   --- 내부 예외 스택 추적의 끝 ---
   위치: System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   위치: RainbowMage.OverlayPlugin.Updater.Installer.<Download>d__8.MoveNext()
Resuming download...
The download was interrupted: System.IO.IOException: 읽기 작업이 실패했습니다. 내부 예외를 참조하세요. ---> System.Net.WebException: 요청이 중단되었습니다. 요청이 취소되었습니다.
   위치: System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   위치: System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   --- 내부 예외 스택 추적의 끝 ---
   위치: System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   위치: RainbowMage.OverlayPlugin.Updater.Installer.<Download>d__8.MoveNext()
Resuming download...


▼▼▼▼▼▼▼▼▼▼▼ MessageBox  : Show ▼▼▼▼▼▼▼▼▼▼▼
Failed to download CEF! You will not be able to use OverlayPlugin. Retry?

**Comment by ngld** [comment]
The updater doesn't have anything to do with the FFXIV plugin. The issue is that .NET seems to have problems downloading the [CEF package](https://github.com/ngld/OverlayPlugin/releases/download/v0.7.0/CefSharp-75.1.14-x64.DO_NOT_DOWNLOAD) over your connection. You can do that manually but it's a bit complicated ([here are the instructions](https://github.com/ngld/OverlayPlugin/issues/26#issuecomment-553737292)). I'll try to improve it so it works better with bad / high latency connections.

**Comment by HAERUHAERU** [comment]
> The updater doesn't have anything to do with the FFXIV plugin. The issue is that .NET seems to have problems downloading the [CEF package](https://github.com/ngld/OverlayPlugin/releases/download/v0.7.0/CefSharp-75.1.14-x64.DO_NOT_DOWNLOAD) over your connection. You can do that manually but it's a bit complicated ([here are the instructions](https://github.com/ngld/OverlayPlugin/issues/26#issuecomment-553737292)). I'll try to improve it so it works better with bad / high latency connections.

Okay, I understand. Perfectly works.

I'm working on an ACT management program that install and delete the plugins. 
I think I need to manually download the CEF package to reduce the exception when installing the overlay plugin. The guided solution is very complicated for the average user.
If possible, can you separate the CEF package into another git?
My program gets the JSON data from [github api](https://api.github.com/repos/ngld/OverlayPlugin/releases). 
The format must always be the same to get the data of latest version .

Also, Do you plan to support the features of ACTWebsocket such as Capture and AppRegion ?
MopiMopi specifically requires the AppRegion feature.

**Comment by ngld** [comment]
> I think I need to manually download the CEF package to reduce the exception when installing the overlay plugin.

I'm working on a better implementation of the download logic (`libcurl` instead of .NET's `WebClient`) and would much rather fix this issue directly in OverlayPlugin than have another program do pretty much the same.

> The guided solution is very complicated for the average user.

Yes, that's why the automated process exists. However, the next version will make this much easier:
![screenshot](https://cdn.discordapp.com/attachments/633499985052172308/647939793359208458/Advanced_Combat_Tracker_2019-11-24_00-21-18.png)
If the automated download fails, the OverlayPlugin.dll tab will show this tab. The `Please wait...` text is just a placeholder which will contain the appropriate download link. The user would click that link and once the file is downloaded, they click the button below, select the downloaded file and OverlayPlugin takes care of the rest.

> If possible, can you separate the CEF package into another git?
> My program gets the JSON data from github api.
> The format must always be the same to get the data of latest version .

I'm not sure if moving that package into another repo would help. You can just loop over the available releases for this repo and look for files starting with `CefSharp-` and you'll be able to find the latest CEF package. Once you have the latest release, you still have to figure out if you want to download the `x86` or `x64` version which depends on whether the user is using the DirectX11 or DirectX9 version of FFXIV.
I might have to change the file extension soon since a few users were surprised by the `.DO_NOT_DOWNLOAD` part. I'll change that to `.CefBundle` with the next update.

That said, you can always find the download URL and expected version in [OverlayPlugin.Updater/CefInstaller.cs](https://github.com/ngld/OverlayPlugin/blob/master/OverlayPlugin.Updater/CefInstaller.cs#L13).

> Also, Do you plan to support the features of ACTWebsocket such as Capture and AppRegion ?
> MopiMopi specifically requires the AppRegion feature.

I can implement the Capture feature fairly easily but I'm not sure about the AppRegion feature. I'll let you know once I figure this out.

**Comment by HAERUHAERU** [comment]
Awesome!! 👍  
It's a great and very kind way to create a manual install tab. 
Thank you for solving the issue yourself. I don't want anything about download anymore. Perfect!  



![GIF](https://user-images.githubusercontent.com/23272956/69490867-e5d2b800-0ed0-11ea-8880-435372a477a3.gif)

AppRegion is a feature that limits the drag area.

MopiMopi does not generate pop-up for the convenience of the mobile experience.
But this uses a lot of sliders and color pickers in the settings.
That's why ACTWebSocket supports it.

---------------------------------------------
MopiMopi.css
nav table {
     -webkit-app-region: drag;
}
OverlayProc: MopiMopi
AppRegion (드래그 영역 사용) ▶ Check
---------------------------------------------

This allows you to move the overlay by dragging only the navigation area. 
Sliders and color pickers are not navigation areas, so dragging won't move the overlay.

**Comment by ngld** [comment]
The AppRegion stuff was easier than expected. I already knew how to use it but I didn't know how to implement that feature since I have to figure out where the draggable areas are and update that information whenever they change. That's not easy but CEF already does most of that work for me so I just had to retrieve that information from CEF and use it in the overlay drag logic.

I'll work on the Capture feature next.

**Comment by HAERUHAERU** [comment]
> The AppRegion stuff was easier than expected. I already knew how to use it but I didn't know how to implement that feature since I have to figure out where the draggable areas are and update that information whenever they change. That's not easy but CEF already does most of that work for me so I just had to retrieve that information from CEF and use it in the overlay drag logic.
> 
> I'll work on the Capture feature next.

Thank you for your hard work. 👍👍👍👍👍 
Is there anything I need to change in mopimopi? I will correct it if there is.
Also I hope that the capture file be saved same path with actwebsocket.
(act folder\\Screenshot)

**Comment by ngld** [comment]
You don't have to change anything in MopiMopi. The only issue I've seen so far is that MopiMopi doesn't update if the player doesn't appear as `YOU` in ACT's table. I don't know if that is intentional or a bug with the ACTWS stuff in OverlayPlugin.
