### ISSUE TITLE
Overlays No Longer Work On Multiple Desktops by Default

### ISSUE THREAD

**Issue by natyusha** [ngld/OverlayPlugin#55]
Something seems to have been changed with this fork of the overlay plugin that makes overlays not obey the "Show windows from this app on all desktops" setting in Windows 10. This means that every time ACT is restarted the "Show this window on all desktops" settings must be set in order to use the overlay plugin on multiple virtual desktops at once.

![ffxiv_dx11_2019-11-26_13-07-51](https://user-images.githubusercontent.com/985941/69660311-070ce300-104e-11ea-8530-b040544b77a7.png)

**Comment by ngld** [comment]
Can you check if the 0.11.2 update fixes this?
If it doesn't, did this work in previous releases from this fork?

**Comment by natyusha** [comment]
In 0.11.2.0 overlays will now show on all desktops which completely solves my problem. It worked in 0.10.1.0 as well.

However, If someone wanted it to show on only one desktop that is not an option as there is no way to change its behavior. It does not follow ACT's settings or display in task view so that one may limit it to only one virtual desktop.

I did not realize that there was no way to stop the overlay from showing on all desktops before since that is what I always wanted it to do.

**Comment by ngld** [comment]
Since the original behavior was restored in 0.11.2, I'd say this bug has been resolved. The fact that it doesn't work with virtual desktops is a separate issue.

If someone doesn't want to see the overlay on other virtual desktops, they can use the auto-hide functions to hide the overlays if the game isn't focused. If they want to see the overlay on that one virtual desktop even while the game isn't focused but not on other virtual desktops... then they're out of luck since that's not supported right now.
