### ISSUE TITLE
Overlay urls sometimes cleared

### ISSUE THREAD

**Issue by quisquous** [ngld/OverlayPlugin#70]
Every once in a while when loading act, overlay urls have been reset back to `about:blank`.

I've seen this happen a few times for me (sometimes only one overlay, once all of them).  Somebody in my raid group reported this just happened to them.  I don't have a repro step for this, but I wonder if there's something awry with the saving or loading step that might be causing this?

**Comment by ngld** [comment]
The URL field for overlays always shows the currently loaded URL (sort of like a real browser) and Chromium instance is started with `about:blank` as the initial URL. Immediately afterwards, the saved URL is loaded so the `about:blank` URL should only be visible for a short time. I've only seen it persist if you close ACT while the overlays are still loading.

Either way, this shouldn't be an issue since the `HtmlRenderer` refactoring since I've changed it to a) load the saved URL immidiately and b) not show `about:blank` in the overlay settings.
I just need to make sure I didn't break anything in the process. Big code changes / rewrites like that are always dangerous (at least for me).

**Comment by quisquous** [comment]
Yeah, this was a persisted state, and I can imagine that it happened because I was doing a lot of starting and stopping act immediately.

If this has been changed such that `about:blank` will never be persisted, then feel free to close this.

**Comment by rauvagol** [comment]
I have a this issue, but it does not resolve itself, after restarting my pc the urls are loaded as about:blank, and stay that way until I manually set them to the desired html file.

**Comment by mooondark** [comment]
I had this problem when my DNS was not working correctly. If the domain name can't be resolved, the url is changed to about:blank.

**Comment by ngld** [comment]
Should be fixed since 0.12.0
