### ISSUE TITLE
DPS update interval seconds question.

### ISSUE THREAD

**Issue by Genesis-Nova** [ngld/OverlayPlugin#90]
Would it be possible to change DPS update interval seconds to be a float instead of an int? I'd like to set the rate that the parse overlay updates to be equal to my frame rate instead of being limited to once per second for presentation purposes as my overlay skin actually has "moving parts" similar to a bar graph..

I believe this was possible in the old overlay plugin but don't quote me on that.

**Comment by ngld** [comment]
I think you're mixing up two settings. There's a DPS update interval that dictates how much time passes between DPS updates. Each update sends the current DPS from ACT's Main tab to the overlays. IMO there's no point in updating those more than once per second.
Each overlay also has a framerate limit (on the Advanced tab). I think you'd want to change that.
The framerate limit defaults to 30 and can be increased to 60 if you want to. 60 is the max limit since Chrome can't render any more than that. Finally, keep in mind that overlay rendering happens on the CPU which means that increasing the framerate limit will also increase ACT's CPU usage.
