### ISSUE TITLE
Overlay Plugin error on startup

### ISSUE THREAD

**Issue by Mr-Sithel** [ngld/OverlayPlugin#97]
Hello! I recently had to reinstall ACT because for whatever reason the FFXIV_ACT plugin was causing an issue. Anyways, now everything is back up and running fine except this error that I'll post below. The problem seems to come from the Overlay Plugin. Even with this error everything is running fine. I blurred out the ip it's trying to connect to because I wasn't sure I should post that.
![act errors](https://user-images.githubusercontent.com/6982111/73030603-a278c500-3dff-11ea-833d-c5845a414df3.PNG)

And the log info:
![act error 3](https://user-images.githubusercontent.com/6982111/73030637-b0c6e100-3dff-11ea-9a82-4cb27f02ae22.PNG)

**Comment by ngld** [comment]
The first message is from the FFXIV plugin, the second is from ACT itself and the final screenshot shows the same error for OverlayPlugin.
They're all caused by the fact that https://advancedcombattracker.com/ is currently unreachable. OverlayPlugin's updater will continue to work though since it uses GitHub's API instead (as the log states).

**Comment by Mr-Sithel** [comment]
Thank you for the quick reply. Makes since, everything just all happened at the same time today and thought I might have messed something up on the reinstall.
